### ISSUE TITLE
Dashboard for testnet

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#67]
We need a dashboard for the testnet that allows casual users some sort of overview and visual status.

It should include:

- [x] netstats
- [x] access to faucet (even if it's just a link)
- [x] basic instructions on how to run a validator

**Comment by rgeraldes** [comment]
1- in order to find if the services running and its info, they do a docker inspect (edited)
2- based on the info of the services they modify a template (hmtl page) with that information 
3- start the server with a docker file.

template (html): https://github.com/kowala-tech/kUSD/blob/dev/cmd/puppeth/module_dashboard.go#L32

docker file: https://github.com/kowala-tech/kUSD/blob/dev/cmd/puppeth/module_dashboard.go#L395

composer: https://github.com/kowala-tech/kUSD/blob/dev/cmd/puppeth/module_dashboard.go#L418
